
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://epkmjxndccxaogiugvcg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwa21qeG5kY2N4YW9naXVndmNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MjUwMzksImV4cCI6MjA2NTIwMTAzOX0.t1Rpr2AZXpbuoWXkSXGUOahHEsw1OOrEhcuUmo0mcow";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Extend supabase with custom RPC for raw queries
declare module '@supabase/supabase-js' {
  interface SupabaseClient {
    rpc(fn: 'custom_query', args: { query_sql: string }): any;
  }
}
